import { useEffect, useRef, useState } from 'react'
import { Activity, ArrowRight, Camera, Check, FileText, LocateFixed, Map, Search, ShieldCheck, Upload, X } from 'lucide-react'
import { assets, geoImages, watersheds } from '../data/mockData'

type FormKind = 'inspection' | 'observation'
type EvidenceRecord = { id: string; place: string; latitude: number; longitude: number; date: string; time: string; officer: string; asset: string; watershed: string; village: string; observation: string; aiSummary: string; internalNotes: string; water: string; condition: string; preview?: string }
type PendingAction = { id: string; action: 'view' | 'analyze' } | null
const samples: EvidenceRecord[] = geoImages.map(image => {
  const asset = assets.find(item => item.id === image.assetId)!
  const watershed = watersheds.find(item => item.id === image.watershedId)!
  const [date, time = '09:00'] = image.capturedAt.split(', ')
  const title = (value: string) => value.charAt(0).toUpperCase() + value.slice(1)
  return { id:image.id, place:image.village, latitude:image.coordinates[0], longitude:image.coordinates[1], date, time, officer:image.capturedBy || 'Field Officer · Prototype', asset:`${asset.id} · ${asset.type}`, watershed:`${watershed.id} · ${watershed.name}`, village:image.village, observation:image.observation || 'A representative geo-coded image is available for review.', aiSummary:`Prototype visual signal: ${image.waterStatus} water status and ${image.condition} condition; field verification recommended.`, internalNotes:'Government-only demo note: compare with the prior capture and confirm on site before recording an official finding.', water:title(image.waterStatus), condition:title(image.condition) }
})
const steps = ['Scanning visual evidence...', 'Reading geo-spatial context...', 'Comparing field indicators...', 'Generating observation...']
const scores: [string, number][] = [['Water Presence', 82], ['Vegetation', 90], ['Structure Damage', 64], ['Possible Erosion', 51]]

export function GovernmentEvidenceExplorer({ onCompare, onViewOnGIS, initialAction, clearInitialAction }: { onCompare: (id: string) => void; onViewOnGIS: (id: string) => void; initialAction: PendingAction; clearInitialAction: () => void }) {
  const [records, setRecords] = useState(samples)
  const [selected, setSelected] = useState<EvidenceRecord | null>(null)
  const [analysis, setAnalysis] = useState<EvidenceRecord | null>(null)
  const [draft, setDraft] = useState<{ record: EvidenceRecord; kind: FormKind } | null>(null)
  const [addOpen, setAddOpen] = useState(false)
  const [notice, setNotice] = useState('')
  const objectUrls = useRef<string[]>([])
  useEffect(() => () => objectUrls.current.forEach(url => URL.revokeObjectURL(url)), [])
  useEffect(() => { if (!initialAction) return; const record = records.find(item => item.id === initialAction.id); if (record) initialAction.action === 'analyze' ? setAnalysis(record) : setSelected(record); clearInitialAction() }, [initialAction, records, clearInitialAction])
  const showNotice = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(''), 4200) }
  const addRecord = (data: { file: File; place: string; latitude: number; longitude: number; observation: string }) => {
    const now = new Date(); const preview = URL.createObjectURL(data.file); objectUrls.current.push(preview)
    const next = Math.max(1028, ...records.map(record => Number(record.id.replace('IMG-', ''))).filter(Number.isFinite)) + 1
    const record: EvidenceRecord = { id: `IMG-${next}`, place: data.place, latitude: data.latitude, longitude: data.longitude, date: new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(now), time: new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit' }).format(now), officer: 'District Officer · Demo', asset: 'WHS-021 · Check Dam', watershed: 'WS-001 · Kovilur Watershed', village: data.place, observation: data.observation, aiSummary: 'Analysis pending. Run AI-assisted visual analysis when ready.', internalNotes: 'Added locally in this browser session for prototype demonstration.', water: 'Pending review', condition: 'Pending review', preview }
    setRecords(current => [record, ...current]); setAddOpen(false); showNotice(`${record.id} added locally for this prototype session.`)
  }
  const saveDraft = (record: EvidenceRecord, kind: FormKind, summary: string, priority: string) => {
    try { const prev = JSON.parse(localStorage.getItem('jal-impact-evidence-drafts') || '[]'); localStorage.setItem('jal-impact-evidence-drafts', JSON.stringify([{ id: `${kind.toUpperCase()}-${Date.now()}`, kind, imageId: record.id, asset: record.asset, summary, priority, savedAt: new Date().toISOString() }, ...prev])) } catch { /* Draft remains visible in the local toast for this session. */ }
    setDraft(null); showNotice(`${kind === 'inspection' ? 'Inspection' : 'Observation'} draft saved for ${record.id} (${priority}).`)
  }
  return <div className="page content-page gov-evidence"><section className="content-hero"><span className="eyebrow">GEO-CODED FIELD EVIDENCE</span><h1>Evidence captured.<br/><i>Intelligence connected.</i></h1><p>GPS-linked images connect field observations to watershed assets and government review.</p><button type="button" className="primary" onClick={() => setAddOpen(true)}><Upload size={17}/> Add field evidence</button></section><div className="evidence-journey"><Camera/> Image <i></i><LocateFixed/> GPS <i></i><Map/> GIS <i></i><span>Watershed</span> <i></i><span>Asset</span> <i></i><Activity/> Analysis</div><section className="gov-evidence-grid">{records.map((record, index) => <article className="gov-evidence-card" key={record.id}><button type="button" className={`gov-image img-${index % 3}`} style={record.preview ? { backgroundImage: `linear-gradient(30deg,#09252d55,transparent),url("${record.preview}")` } : undefined} onClick={() => setSelected(record)} aria-label={`View ${record.id}`}><span><Camera size={14}/> {record.id}</span><em><LocateFixed size={13}/> GPS verified</em><i><Search size={18}/></i></button><div className="gov-evidence-info"><div className="evidence-id"><span>{record.id}</span><small>GOVERNMENT FIELD EVIDENCE</small></div><h3>{record.place}</h3><p><LocateFixed size={14}/> {record.latitude.toFixed(6)}, {record.longitude.toFixed(6)}</p><p><Camera size={14}/> {record.date} · {record.time}</p><div className="evidence-meta"><span>Asset <b>{record.asset.split(' · ')[0]}</b></span><span>Water <b className={record.water === 'Poor' ? 'red-text' : 'amber-text'}>{record.water}</b></span><span>Condition <b className="amber-text">{record.condition}</b></span></div><footer><button type="button" onClick={() => setSelected(record)}>View</button><button type="button" onClick={() => setAnalysis(record)}>Analyze</button><button type="button" onClick={() => onCompare(record.id)}>Compare</button><button type="button" onClick={() => onViewOnGIS(record.id)}>View on GIS</button></footer></div></article>)}</section>{notice && <div className="toast" role="status"><Check size={15}/>{notice}</div>}{selected && <GovernmentImageDetail record={selected} close={() => setSelected(null)} analyze={() => setAnalysis(selected)} compare={() => onCompare(selected.id)} viewOnGIS={() => onViewOnGIS(selected.id)} onAction={kind => setDraft({ record: selected, kind })}/ >}{analysis && <AnalysisModal record={analysis} close={() => setAnalysis(null)}/ >}{draft && <DraftModal record={draft.record} kind={draft.kind} close={() => setDraft(null)} onSave={(summary, priority) => saveDraft(draft.record, draft.kind, summary, priority)}/ >}{addOpen && <AddEvidenceModal close={() => setAddOpen(false)} onSave={addRecord}/>}</div>
}

function GovernmentImageDetail({ record, close, analyze, compare, viewOnGIS, onAction }: { record: EvidenceRecord; close: () => void; analyze: () => void; compare: () => void; viewOnGIS: () => void; onAction: (kind: FormKind) => void }) {
  const index = Math.max(0, samples.findIndex(item => item.id === record.id)) % 3
  const preview = record.preview ? { backgroundImage: `linear-gradient(30deg,#09252d22,transparent),url("${record.preview}")` } : undefined
  return <div className="image-modal government-evidence-modal" onClick={close}><article onClick={event => event.stopPropagation()} role="dialog" aria-modal="true" aria-label={`${record.id} evidence details`}><button type="button" className="modal-close" onClick={close} aria-label="Close details"><X/></button><div className={`gov-detail-image img-${index}`} style={preview}><span><Camera size={14}/> FIELD IMAGE · PROTOTYPE SAMPLE</span></div><div className="gov-detail-heading"><div><span className="eyebrow">GOVERNMENT IMAGE EXPLORER</span><h2>{record.id} · {record.place}</h2></div><span className="evidence-badge"><ShieldCheck size={13}/> GPS linked</span></div><div className="gov-detail-facts"><span><small>Capture date & time</small><b>{record.date} · {record.time}</b></span><span><small>GPS coordinates</small><b>{record.latitude.toFixed(6)}, {record.longitude.toFixed(6)}</b></span><span><small>Officer</small><b>{record.officer}</b></span><span><small>Watershed</small><b>{record.watershed}</b></span><span><small>Village</small><b>{record.village}</b></span><span><small>Asset</small><b>{record.asset}</b></span></div><section className="gov-detail-section"><h3><FileText size={15}/> Field observation</h3><p>{record.observation}</p></section><section className="gov-analysis-summary"><h3><Activity size={15}/> AI-assisted analysis</h3><p>{record.aiSummary}</p><small>AI-assisted visual observation. Field verification recommended.</small></section><section className="gov-internal-note"><h3><ShieldCheck size={15}/> Internal notes · Government only</h3><p>{record.internalNotes}</p></section><div className="gov-evidence-actions"><button type="button" className="primary" onClick={analyze}><Activity size={15}/> Analyze</button><button type="button" onClick={compare}>Compare</button><button type="button" onClick={viewOnGIS}><Map size={15}/> View on GIS</button><button type="button" onClick={() => onAction('inspection')}>Create Inspection</button><button type="button" onClick={() => onAction('observation')}>Create Observation</button></div></article></div>
}

function AnalysisModal({ record, close }: { record: EvidenceRecord; close: () => void }) {
  const [step, setStep] = useState(0)
  useEffect(() => { if (step >= steps.length) return; const timer = window.setTimeout(() => setStep(value => value + 1), 720); return () => window.clearTimeout(timer) }, [step])
  return <div className="image-modal ai-analysis-modal" onClick={close}><article onClick={event => event.stopPropagation()} role="dialog" aria-modal="true" aria-label={`Analysis for ${record.id}`}><button type="button" className="modal-close" onClick={close} aria-label="Close analysis"><X/></button><span className="eyebrow">AI-ASSISTED VISUAL ANALYSIS</span><h2>{record.id} · {record.place}</h2><p className="analysis-context"><LocateFixed size={13}/> {record.latitude.toFixed(6)}, {record.longitude.toFixed(6)} · {record.asset}</p>{step < steps.length ? <><div className="analysis-steps">{steps.map((label, index) => <div key={label} className={`analysis-step ${index < step ? 'done' : index === step ? 'active' : ''}`}><span>{index < step ? <Check size={13}/> : index + 1}</span><b>{label}</b></div>)}</div><div className="analysis-loading-state"><span className="ripple-loader"><i></i><i></i><i></i></span><b>Analyzing visual evidence...</b><small>Prototype analysis; it does not submit or verify an official record.</small></div></> : <div className="analysis-results"><span className="analysis-outcome">Possible degradation observed.</span>{scores.map(([label, score], index) => <div className="analysis-result" key={label}><div><span>{label}</span><b>{score}%</b></div><div className="ai-analysis-bar"><i style={{ width: `${score}%`, animationDelay: `${index * 110}ms` }}/></div></div>)}<p className="analysis-disclaimer">AI-assisted visual observation. Field verification recommended.</p><p className="analysis-disclaimer">AI-assisted visual observation. Results require field verification and should not be treated as official ground truth.</p></div>}<button type="button" className="primary analysis-close" onClick={close}>Close analysis</button></article></div>
}

function DraftModal({ record, kind, close, onSave }: { record: EvidenceRecord; kind: FormKind; close: () => void; onSave: (summary: string, priority: string) => void }) {
  const [summary, setSummary] = useState(''); const [priority, setPriority] = useState('Routine')
  return <div className="gov-modal-backdrop" onClick={close}><form className="gov-action-modal" onClick={event => event.stopPropagation()} onSubmit={event => { event.preventDefault(); onSave(summary.trim(), priority) }}><button type="button" className="modal-close" onClick={close} aria-label="Close draft"><X/></button><span className="eyebrow">{kind === 'inspection' ? 'NEW INSPECTION' : 'NEW OBSERVATION'}</span><h2>{kind === 'inspection' ? 'Create inspection draft' : 'Create field observation'}</h2><p>{record.id} · {record.asset} · {record.place}</p><label>{kind === 'inspection' ? 'Inspection focus' : 'Observation'}<textarea required minLength={3} value={summary} onChange={event => setSummary(event.target.value)} placeholder="Describe what should be checked or recorded"/></label><label>Priority<select value={priority} onChange={event => setPriority(event.target.value)}><option>Routine</option><option>Medium</option><option>High</option></select></label><small className="prototype-form-note">Saved locally as a prototype draft; no external record is submitted.</small><button type="submit" className="primary">Save draft <ArrowRight size={15}/></button></form></div>
}

function AddEvidenceModal({ close, onSave }: { close: () => void; onSave: (data: { file: File; place: string; latitude: number; longitude: number; observation: string }) => void }) {
  const [file, setFile] = useState<File | null>(null); const [place, setPlace] = useState('Kovilur'); const [latitude, setLatitude] = useState('12.970000'); const [longitude, setLongitude] = useState('80.006000'); const [observation, setObservation] = useState(''); const [error, setError] = useState('')
  return <div className="gov-modal-backdrop" onClick={close}><form className="gov-action-modal add-evidence-modal" onClick={event => event.stopPropagation()} onSubmit={event => { event.preventDefault(); if (!file) { setError('Choose an image file to continue.'); return } onSave({ file, place: place.trim() || 'Kovilur', latitude: Number(latitude), longitude: Number(longitude), observation: observation.trim() }) }}><button type="button" className="modal-close" onClick={close} aria-label="Close upload"><X/></button><span className="eyebrow">GOVERNMENT IMAGE EXPLORER</span><h2>Add field evidence</h2><p>Attach an image and location context. The record stays in this browser session.</p><label className="evidence-file-picker"><Upload size={18}/><span>{file ? file.name : 'Choose an image file'}</span><input required type="file" accept="image/*" onChange={event => { setFile(event.target.files?.[0] || null); setError('') }}/></label><div className="evidence-form-grid"><label>Village / location<input required value={place} onChange={event => setPlace(event.target.value)}/></label><label>Latitude<input required type="number" step="any" value={latitude} onChange={event => setLatitude(event.target.value)}/></label><label>Longitude<input required type="number" step="any" value={longitude} onChange={event => setLongitude(event.target.value)}/></label></div><label>General observation<textarea required minLength={3} value={observation} onChange={event => setObservation(event.target.value)} placeholder="What is visible in the field image?"/></label>{error && <small className="evidence-form-error" role="alert">{error}</small>}<button type="submit" className="primary">Add to local evidence list <ArrowRight size={15}/></button></form></div>
}
